export const ERROR = 'ERROR';
export const UPDATE_ERROR = 'UPDATE_ERROR';

export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const RETRIEVE_EMPLOYEES = 'RETRIEVE_EMPLOYEES';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const DELETE_ALL_EMPLOYEES = 'DELETE_ALL_EMPLOYEES';

export const CREATE_TAG = 'CREATE_TAG';
export const RETRIEVE_TAGS = 'RETRIEVE_TAGS';
export const UPDATE_TAG = 'UPDATE_TAG';
export const DELETE_TAG = 'DELETE_TAG';
export const DELETE_ALL_TAGS = 'DELETE_ALL_TAGS';

export const CREATE_SHIFT = 'CREATE_SHIFT';
export const RETRIEVE_SHIFTS = 'RETRIEVE_SHIFTS';
export const UPDATE_SHIFT = 'UPDATE_SHIFT';
export const DELETE_SHIFT = 'DELETE_SHIFT';
export const DELETE_ALL_SHIFTS = 'DELETE_ALL_SHIFTS';

export const CREATE_BUSINESS = 'CREATE_BUSINESS';
export const RETRIEVE_BUSINESS = 'RETRIEVE_BUSINESS';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
export const DELETE_BUSINESS = 'DELETE_BUSINESS';
export const DELETE_ALL_BUSINESS = 'DELETE_ALL_BUSINESS';