export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const RETRIEVE_EMPLOYEES = 'RETRIEVE_EMPLOYEES';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const DELETE_ALL_EMPLOYEES = 'DELETE_ALL_EMPLOYEES';

export const CREATE_ROLE = 'CREATE_ROLE';
export const RETRIEVE_ROLES = 'RETRIEVE_ROLES';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const DELETE_ALL_ROLES = 'DELETE_ALL_ROLES';

export const CREATE_SHIFT = 'CREATE_SHIFT';
export const RETRIEVE_SHIFTS = 'RETRIEVE_SHIFTS';
export const UPDATE_SHIFT = 'UPDATE_SHIFT';
export const DELETE_SHIFT = 'DELETE_SHIFT';
export const DELETE_ALL_SHIFTS = 'DELETE_ALL_SHIFTS';